# 🦞 Claw Agent - Chrome Extension Setup
# Reads local env values and generates a local-only helper script for
# configuring the Chrome extension's sync storage.

[CmdletBinding()]
param()

Write-Host "🦞 Claw Agent - Chrome Extension Setup" -ForegroundColor Green
Write-Host ("=" * 60)
Write-Host ""

$envPath = Join-Path $PSScriptRoot ".env.local"
$nvidiaApiKey = ""
$dashScopeKey = ""
$model = "qwen3.5-397b-a17b"

Write-Host "📖 Reading API keys from .env.local..." -ForegroundColor Cyan

if (-not (Test-Path $envPath)) {
    Write-Host "   ❌ .env.local not found" -ForegroundColor Red
    exit 1
}

$content = Get-Content $envPath -Raw

if ($content -match '(?m)^(?:NVIDIA_API_KEY|NIM_API_KEY)=["'']?([^"''\r\n]+)["'']?$') {
    $nvidiaApiKey = $matches[1]
    Write-Host "   ✅ NVIDIA key found" -ForegroundColor Green
}

if ($content -match '(?m)^DASHSCOPE_API_KEY=["'']?([^"''\r\n]+)["'']?$') {
    $dashScopeKey = $matches[1]
    Write-Host "   ✅ DashScope key found" -ForegroundColor Green
}

if (-not $nvidiaApiKey) {
    Write-Host "   ❌ NVIDIA_API_KEY or NIM_API_KEY not found in .env.local" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "⚙️  Preparing local helper script..." -ForegroundColor Cyan

$configData = @{
    nvidia_api_key = $nvidiaApiKey
    dashscope_api_key = $dashScopeKey
    current_model = $model
    settings_loaded = $true
    loaded_at = (Get-Date -Format "o")
}

$configJson = $configData | ConvertTo-Json -Depth 10 -Compress
$localLoaderPath = Join-Path $PSScriptRoot "chrome-extension\AUTO_LOAD_KEYS.local.js"

$loaderScript = @"
// Auto-generated by setup-chrome-extension.ps1
// Local helper only. Do not commit this file.

(async function autoLoadApiKeys() {
  const config = $configJson;

  try {
    await chrome.storage.sync.set(config);

    console.log('✅ Claw Agent configured');
    console.log('   Model:', config.current_model);
    console.log('   NVIDIA:', config.nvidia_api_key.substring(0, Math.min(15, config.nvidia_api_key.length)) + '...');
    if (config.dashscope_api_key) {
      console.log('   DashScope:', config.dashscope_api_key.substring(0, Math.min(15, config.dashscope_api_key.length)) + '...');
    }
    console.log('🔄 Reload the extension after saving.');

    chrome.runtime.sendMessage({ type: 'settings-updated', ...config });
  } catch (error) {
    console.error('❌ Failed to save extension settings:', error);
  }
})();
"@

$loaderScript | Out-File -FilePath $localLoaderPath -Encoding UTF8
Write-Host "   ✅ Local helper created: chrome-extension\\AUTO_LOAD_KEYS.local.js" -ForegroundColor Green

Write-Host ""
Write-Host "📋 Next steps" -ForegroundColor Yellow
Write-Host ""
Write-Host "   1. Open chrome://extensions/" -ForegroundColor White
Write-Host "   2. Reload 'Claw Agent'" -ForegroundColor White
Write-Host "   3. Open the Claw side panel" -ForegroundColor White
Write-Host "   4. Right-click the panel -> Inspect" -ForegroundColor White
Write-Host "   5. Open chrome-extension\\AUTO_LOAD_KEYS.local.js" -ForegroundColor White
Write-Host "   6. Copy all content -> paste into the DevTools console -> press Enter" -ForegroundColor White
Write-Host "   7. Reload the extension once more" -ForegroundColor White

Write-Host ""
Write-Host ("=" * 60) -ForegroundColor Cyan
Write-Host ""
Write-Host "🎉 SETUP READY" -ForegroundColor Green
Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "   Model: $model" -ForegroundColor White
Write-Host "   NVIDIA: $($nvidiaApiKey.Substring(0, [Math]::Min(15, $nvidiaApiKey.Length)))..." -ForegroundColor White
if ($dashScopeKey) {
    Write-Host "   DashScope: $($dashScopeKey.Substring(0, [Math]::Min(15, $dashScopeKey.Length)))..." -ForegroundColor White
}
Write-Host ""
Write-Host "Local helper file:" -ForegroundColor Cyan
Write-Host "   $localLoaderPath" -ForegroundColor Gray
Write-Host ""
Write-Host "Press any key to exit..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
